### ISSUE TITLE
Issue while scraping

### ISSUE THREAD

**Issue by Hiranmagic** [rafikahmed/web-scraping-course#1]
Hi Ahmed,

I was trying to scrape a website to extract data as part of learning . Th problem is that I am unable to extract the url's correctly.

I am pasting the code for your  kind perusal.
=====> code begins
import scrapy

class GoodReadsSpider(scrapy.Spider):
    #identity
    name = "holidayiqmp"

    #Request
    start_urls= [
        'https://www.holidayiq.com/Manali-Sightseeing-451.html'
    ]

    #Response
    def parse(self, response):
        for holiday in response.selector.xpath("//div[@class='media-body']"):
                            
            yield {
                
                'Name': holiday.xpath(".//h2[@class='media-heading']/text()").extract_first(),
                'Type': holiday.xpath(".//h2[@class='media-heading']//span/text()").extract_first(),
                'url' : holiday.xpath("//div[@class='infinite-scroll-example__scrollable-parent wpscroll']/div/a/@href").extract(),
                
            }

<=======Code ends.

I an able to get Name and Type as expected. I am having problems with URL's. 
Please help me resolve this.
Thanks,
Hiran

**Comment by rafikahmed** [comment]
Hello Hiran, 
I tested your code and I spotted a couple of mistakes in your XPath expressions, I understand XPath can be really hard for those who just started with it, but don't worry It will be easy by time and practicing.
So first I see that you are looping through all div's that have the class attribute set to media-body and then your are extracting all the div's that have the class attribute set to ' class='infinite-scroll-example__scrollable-parent wpscroll' to get the links.
Now the problem is **the div with the class attribute set to 'class='infinite-scroll-example__scrollable-parent wpscroll' is located outside the div that has the class attribute set to media-body, this is why you are not getting the data correctly.** 
![mistake](https://user-images.githubusercontent.com/41229637/49703646-ba938200-fc07-11e8-934e-5c920e2836da.PNG)

The second mistake I saw is within the type xpath expression: './/h2[@class='media-heading']//span/text()' before the span node you used double slash '//'.
Now here is my fix with the correct XPath expressions: 
```
import scrapy

class GoodReadsSpider(scrapy.Spider):
    #identity
    name = "holidayiqmp"

    #Request
    start_urls= [
        'https://www.holidayiq.com/Manali-Sightseeing-451.html'
    ]

    #Response
    def parse(self, response):
        for holiday in response.selector.xpath("//div[@class='infinite-scroll-example__scrollable-parent wpscroll']/div"):         
            yield {  
                'Name': holiday.xpath(".//h2[@class='media-heading']/text()").extract_first(),
                'Type': holiday.xpath(".//h2[@class='media-heading']/span/text()").extract_first(),
                'url' : holiday.xpath(".//a/@href").extract_first()
                
            }

```
Here is the output I got: 
```
[
    {
        "Name": "Rohtang Pass",
        "Type": "Mountain",
        "url": "https://www.holidayiq.com/Rohtang-Pass-Manali-Sightseeing-451-8189.html"
    },
    {
        "Name": "Solang Valley",
        "Type": "Valley",
        "url": "https://www.holidayiq.com/Solang-Valley-Manali-Sightseeing-451-1347.html"
    },
    {
        "Name": "Manikaran Gurudwara",
        "Type": "Gurudwara",
        "url": "https://www.holidayiq.com/Manikaran-Gurudwara-Manali-Sightseeing-451-18630.html"
    },
    {
        "Name": "Hadimba Temple",
        "Type": "Temple",
        "url": "https://www.holidayiq.com/Hadimba-Temple-Manali-Sightseeing-451-68.html"
    },
    {
        "Name": "River Beas",
        "Type": "River",
        "url": "https://www.holidayiq.com/River-Beas-Manali-Sightseeing-451-18629.html"
    },
    {
        "Name": "The Mall Road",
        "Type": "Street",
        "url": "https://www.holidayiq.com/The-Mall-Road-Manali-Sightseeing-451-34440.html"
    },
    {
        "Name": "Gulaba",
        "Type": "Picnic Spot",
        "url": "https://www.holidayiq.com/Gulaba-Manali-Sightseeing-451-1349.html"
    },
    {
        "Name": "Old Manali",
        "Type": "Village",
        "url": "https://www.holidayiq.com/Old-Manali-Manali-Sightseeing-451-12700.html"
    },
    {
        "Name": "Manu Temple",
        "Type": "Temple",
        "url": "https://www.holidayiq.com/Manu-Temple-Manali-Sightseeing-451-69.html"
    },
    {
        "Name": "Rahala Falls",
        "Type": "Water Fall",
        "url": "https://www.holidayiq.com/Rahala-Falls-Manali-Sightseeing-451-1346.html"
    },
    {
        "Name": "Jagatsukh",
        "Type": "Temple",
        "url": "https://www.holidayiq.com/Jagatsukh-Manali-Sightseeing-451-12684.html"
    },
    {
        "Name": "Kothi",
        "Type": "Village",
        "url": "https://www.holidayiq.com/Kothi-Manali-Sightseeing-451-12687.html"
    },
    {
        "Name": "Vashist Springs And Temple",
        "Type": "Temple",
        "url": "https://www.holidayiq.com/Vashist-Springs-And-Temple-Manali-Sightseeing-451-1344.html"
    },
    {
        "Name": "Bhrigu Lake",
        "Type": "Lake",
        "url": "https://www.holidayiq.com/Bhrigu-Lake-Manali-Sightseeing-451-1352.html"
    },
    {
        "Name": "Great Himalayan National Park",
        "Type": "National Park",
        "url": "https://www.holidayiq.com/Great-Himalayan-National-Park-Manali-Sightseeing-451-12691.html"
    },
    {
        "Name": "Hamta Pass",
        "Type": "Water Fall",
        "url": "https://www.holidayiq.com/Hamta-Pass-Manali-Sightseeing-451-12707.html"
    },
    {
        "Name": "Manali Wildlife Parks",
        "Type": "Sanctuary",
        "url": "https://www.holidayiq.com/Manali-Wildlife-Parks-Manali-Sightseeing-451-1350.html"
    },
    {
        "Name": "Rozy Falls",
        "Type": "Water Fall",
        "url": "https://www.holidayiq.com/Rozy-Falls-Manali-Sightseeing-451-12699.html"
    },
    {
        "Name": "Bijli Mahadev Temple",
        "Type": "Temple",
        "url": "https://www.holidayiq.com/Bijli-Mahadev-Temple-Manali-Sightseeing-451-12693.html"
    },
    {
        "Name": "Gadhan Thekchhokling Gompa",
        "Type": "Monastery",
        "url": "https://www.holidayiq.com/Gadhan-Thekchhokling-Gompa-Manali-Sightseeing-451-12694.html"
    }
]
```
Hope my response is clear to you.
Kind regards,
Ahmed.

**Comment by Hiranmagic** [comment]
Thanks a lot Ahmed. It was very helpful and the response was super-quick.

Warm regards,
Hiran
