### ISSUE TITLE
infinite scroll pagination

### ISSUE THREAD

**Issue by Hiranmagic** [rafikahmed/web-scraping-course#2]
Hi Ahmed,
Thanks for the prompt reply for a previous query that I posted in your GitHub account.  
Right now, I am facing another issue with dynamic pagination. I was trying to replicate the Airbnb.com example and wanted to do similar activity in holidayiq.com.
My objective is to scrape the review comments for one location in Holidayiq.com. 

The url is : https://www.holidayiq.com/page/Rohtang-Pass-Manali-Sightseeing-451-8189-p2.html

When I try to open the fetch type in XHR to a new tab to get the json file it throws an error. I am unable to proceed. Could you please  help me resolve this issue.

Thanks in advance,
Hiran

**Comment by rafikahmed** [comment]
Hi Hiran,
I already responded to your question on Udemy.
Kind regards,
Ahmed Wednesday, 12 December 2018, 08:26pm +01:00 from Hiranmagic  notifications@github.com :
